config/routes.rb
  post "subcategory/save"
  post "subcategory/update"
  get "subcategory/edit"
  get "subcategory/new"
  get "subcategory/destroy"
  post "subcategory/destroy"  
  
  
  get "article/index"
  get "article/show"
  get "article/list"
  get "article/comment"
  post "article/comment"
  get "article/new"
  post "article/save"
  get "article/edit"
  post "article/update"
  get "article/news"
  get "article/destroy"
  post "article/destroy"
    get "article/delete"
  post "article/delete"
  match '/getBlogcategory' => 'article#getBlogcategory'
  match '/thumbsUp' => 'article#thumbsUp'
  match '/thumbsDown' => 'article#thumbsDown'
  match '/delete_comment' => 'article#delete_comment'
  
  get "blog_category/index"
  get "blog_category/list"
  get "blog_category/show"
  post "blog_category/save"
  post "blog_category/update"
  get "blog_category/edit"
  get "blog_category/destroy"
  post "blog_category/destroy"
  get "blog_category/new"
  match '/subcategory' => 'blog_category#subcategory'
  match '/subcategory_article' => 'blog_category#subcategory_article' 
  match '/blog' => 'blog_category#blog' 
  match '/categoryArticle' => 'blog_category#categoryArticle'

  
  
  resources :users do
   get :autocomplete_user_name, :on => :collection
  end
  
  resources :folders
  get "folders/index"
  get "folders/new"
  get "folders/create"
  post "folders/create"
  get "assets/destroy"
  post "assets/destroy"  
  match "browse/:folder_id" => "folders#browse", :as => "browse"  
  match "browse/:folder_id/new_folder" => "folders#new", :as => "new_sub_folder"    
  match "browse/:folder_id/new_file" => "assets#new", :as => "new_sub_file"
  match "browse/:folder_id/rename" => "folders#edit", :as => "rename_folder"
  match '/getName' => 'folders#getName'
  match '/unshareFolder' => 'folders#unshareFolder'
  
  resources :assets 
  get "assets/index"
  get "assets/new"
  get "assets/create"
  post "assets/create"
  get "assets/destroy"
  post "assets/destroy"
match "assets/get/:id" => "assets#get", :as => "download"  
  match "assets/share" => "assets#share"
  match "assets/unshare" => "assets#unshare"
  match '/lock' => 'assets#lock'
  match '/unlock' => 'assets#unlock'  
  
  
  
  
resources :aboutus
resources :clientinfo
  resources :images 

  match '/view_aboutus' => 'home#view_aboutus'
  match '/view_clients' => 'home#view_clients'
  match '/view_features' => 'home#view_features'
  match '/view_modules' => 'home#view_modules'
  match '/view_contactus' => 'home#view_contactus'
  
  match '/deleteUsersubject' => 'users#deleteUsersubject'

match '/clientImage' => 'images#clientImage'
match '/createClientimage' => 'images#createClientimage'

  get "/questions/question_type_listing"
  post "/questions/new"
  resources :questions do
        member do
          get "delete_option"
      post "delete_option"
                get "delete_match_option"
      post "delete_match_option"
                      get "delete_matrix_row"
      post "delete_matrix_row"
                      get "delete_matrix_column"
      post "delete_matrix_column"
      get "delete_hrcl_option"
      post "delete_hrcl_option"
      
            get "saveImage"
      post "saveImage"
      
    end
  end
  match '/publish_unpublish' => 'questions#publish_unpublish'
  match '/unpublish' => 'questions#unpublish'
  match '/share' => 'questions#share' 

  match '/saveImage' => 'questions#saveImage'
   match '/sharewithCategory' => 'questions#sharewithCategory'
  match'/checkMark' => 'questions#checkMark'
   match'/viewQuestion' => 'questions#viewQuestion'
   
  get "subjects/add_subject_category"
  resources :subjects 
  
  post "subjects/cs"
  
  resources :categories
  resources :category_titles
  resources :emails  
    
  post "attend_exams/confirm_exam"
  get "attend_exams/confirm_exam"
  post "attend_exams/reject_exam"
  get "attend_exams/reject_exam"
  resources :attend_exams
  get "attend_exams/index"
  match '/examination' => 'attend_exams#examination'
  match '/instruction' => 'attend_exams#instruction'
  match '/evaluation' => 'attend_exams#evaluation'
  match '/evaluation' => 'attend_exams#ramdomizeQuestions'
   match '/examComplete' => 'attend_exams#examComplete'
   match '/calculateScore' => 'attend_exams#calculateScore'
   match '/windowClose' => 'attend_exams#windowClose'
   
   
   match 'welcome/examinee_dashboard' => 'welcome#examinee_dashboard'

  resources :exams 
  match '/scheduleExam' => 'exams#scheduleExam'
  match '/selectQuestion' => 'exams#selectQuestion'
  match '/assignQustions' => 'exams#assignQustions'
  match '/selectExaminee' => 'exams#selectExaminee'
  match '/assignExaminees' => 'exams#assignExaminees'
  match '/previewExam' => 'exams#previewExam'
  match '/deleteExamQuestion' => 'exams#deleteExamQuestion'
  match '/deleteExamUser' => 'exams#deleteExamUser'
 match '/getMark' => 'exams#getMark'
 match '/assignExam' => 'exams#assignExam'
  match '/groupExam' => 'exams#groupExam'
 match '/updateMark' => 'exams#updateMark'
  match '/examtype' => 'exams#examtype'
   match '/create_examtype' => 'exams#create_examtype'
   match '/listExamtypes' => 'exams#listExamtypes'
  match '/editExamtype' => 'exams#editExamtype' 
   match '/deleteExamtype' => 'exams#deleteExamtype' 
   match '/updateExamtype' => 'exams#updateExamtype' 
match '/getExam' => 'exams#getExam'
 match '/showEvaluationtype' => 'exams#showEvaluationtype'
 match '/hideEvaluationtype' => 'exams#hideEvaluationtype'
 match '/evaluate' => 'exams#evaluate'
 match '/getExamQuestions' => 'exams#getExamQuestions'
 match '/manualEvaluation' => 'exams#manualEvaluation'
 match '/finishEvaluation' => 'exams#finishEvaluation'
 match '/getCategoryexams' => 'exams#getCategoryexams'
 match '/assignEvaluator' => 'exams#assignEvaluator'
  match '/getEvaluator' => 'exams#getEvaluator'
  match '/evaluator' => 'exams#evaluator'
  match '/delete_evaluator' => 'exams#delete_evaluator' 
  
 match '/completedExams' => 'attend_exams#completedExams'
 match '/pendingExams' => 'attend_exams#pendingExams'
 
 
  
  match '/updateCategory' => 'category_titles#updateCategory'
  match '/deleteCategory' => 'category_titles#deleteCategory'
  
  get "settings/index"
  post "settings/update"
  
  get "feedback/index"
  match '/assign' => 'feedback#assign'
  match '/unassign' => 'feedback#unassign'
  match '/viewFeedback' => 'feedback#viewFeedback'
  match '/submitFeedback' => 'feedback#submitFeedback'
  match '/viewfeedbackResponse' => 'feedback#viewfeedbackResponse'
  match '/feedbackResponse' => 'feedback#feedbackResponse'
    

  get "reports/index"
  
  get "results/index"
  match '/usersResult' => 'results#usersResult'
  match '/resultIndex' => 'results#index'
  match '/viewUserResult' => 'results#viewUserResult'
  match '/groupResult' => 'results#groupResult'
  match '/examsResult' => 'results#examsResult'
  match '/viewExamResult' => 'results#viewExamResult'
  match '/departmentResult' => 'results#departmentResult'
  match '/viewDepartmentResult' => 'results#viewDepartmentResult'
  
  
  
  match '/userReport' => 'reports#userReport'
  match '/viewuserReport' => 'reports#viewuserReport'
 match '/examReport' => 'reports#examReport'
match '/viewexamReport' => 'reports#viewexamReport'
match '/generateUser' => 'reports#generateUser'
match '/userSubjectwise' => 'reports#userSubjectwise'
match '/generateExamReport' => 'reports#generateExamReport'
match '/departmentReport' => 'reports#departmentReport'
match '/viewDepartmentReport' => 'reports#viewDepartmentReport'
match '/generateDepartmentReport' => 'reports#generateDepartmentReport'
match '/viewDepartmentReportgraph' => 'reports#viewDepartmentReportgraph'
match '/highLevel' => 'reports#highLevel'
match '/reportYear' => 'reports#reportYear'
match '/overall' => 'reports#overall'
match '/specificDepartment' => 'reports#specificDepartment'
match '/departmentDetailed' => 'reports#departmentDetailed'
match '/semesterDetailed' => 'reports#semesterDetailed'
match '/pass_fail' => 'reports#pass_fail'
match '/generatePassfail' => 'reports#generatePassfail'
match '/fetchExam' => 'reports#fetchExam'

match '/listCategories' => 'categories#listCategories'
match '/delete_category' => 'categories#delete_category'



  get "questions/index"

  get "subjects/index"


  resources :temporary_examinee


  resources :user_registration

  
  get "welcome/index"
  get "welcome/admin_dashboard"
  get "welcome/examiner_dashboard"
  get "welcome/qsetter_dashboard"
  get "welcome/examinee_dashboard"
  post "welcome/confirm_registration"
  get "welcome/confirm_registration"
  post "welcome/reject_registration"
  get "welcome/reject_registration"
  get "welcome/user_management"
  get "welcome/workflow"
  
  get "passwords/new"

  match 'groupUser' => 'users#groupUser'
  match 'createGroup' => 'users#createGroup'
  get "user_sessions/new"

  get "users/new"
  get "users/generate_temporary_password"
  post "users/generate_temporary_password"
  match 'activate_inactivate' => 'users#activate_inactivate'
    match 'activate' => 'users#activate'
      match 'inactivate' => 'users#inactivate'

  resources :users 
  get "users/show"

  get "users/edit"
  
  
  get "home/index"

  get "user_sessions/new"
  resources :user_sessions
 
  match 'login' => "user_sessions#new",      :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout
    
  resources :password_resets do
    member do
      get 'confirmEmail'
      get 'setPassword'
      get 'savePassword'
      post 'savePassword'
      get 'verifyPassword'      
    end
  end
  get "password_resets/edit"



  get    'verify/:id'       => 'user_verifications#index'
  








    root :to => 'home#index'

app/models/report.rb
class Report < ActiveRecord::Base
  belongs_to :user
  belongs_to :report_type
  

  
end

app/models/report_type.rb
class ReportType < ActiveRecord::Base
  has_many :reports
end

app/helpers/reports_helper.rb
module ReportsHelper
  
  def descriptive_help(text)
    #include ActionView::Helpers::SanitizeHelper  
    #strip_tags(text)#.to_s.gsub(/(<[^>]+>|&nbsp;|\r|\n|&prod;|<sup>)/,"")
    @a = content_tag :span, "#{text}".html_safe
    return @a
  end
end

app/views/reports/_collect_exams.html.erb
<div class="updateStatus">
	<h2><%=t('exam.exams')%></h2>
<table border="0" cellspacing="0">
<tr class="updateHeader">
<th><%=t('general.name')%></th>

<th><%=t('reports.view_report')%></th>
<th><%=t('reports.excel')%></th>
<th><%=t('reports.pdf')%></th>
</tr>

<%@category_exam.each do|catexam|%>
<tr class="updateAltrRow <%= cycle("odd", "even") %>">
<% exam = Exam.find_by_id(catexam.exam_id)%>
<td><%=exam.name%></td>


<td>
<%category = Category.find_by_id(catexam.category_id)%>
<%semesterId = category.semester_id%>
<%= link_to t('general.view'), :action =>"viewexamReport", :exam_id=>exam.id,:category_id=>@category_id, :examType=>@examtype, :currentyear=>@academicYear %>

<%#= link_to "View", :action =>"viewexamReport", :exam_id=>exam.id, :semester_id=>semesterId %>
</td>
<td>
	<%= link_to image_tag("excel.png", :alt=>"excel report"), :action=>"generateExamReport", :exam_id=>exam.id,:category_id=>@category_id, :examType=>@examtype, :currentyear=>@academicYear, :csv=>1%>

</td>
<td>
	<%= link_to image_tag("pdf.png", :alt=>"pdf report"), :action=>"generateExamReport", :exam_id=>exam.id,:category_id=>@category_id, :examType=>@examtype, :currentyear=>@academicYear, :pdf=>1%>

</td>
</tr>
<%end%>

</table>

</div>

app/views/reports/_collect_users.html.erb
<div class="updateStatus">
	<h2><%=t('user.examinees')%></h2>
<table border="0" cellspacing="0">
<tr class="updateHeader">
<th><%=t('general.name')%></th>
<th><%=t('reports.view_report')%></th>
<th><%=t('reports.excel')%></th>
<th><%=t('reports.pdf')%></th>
</tr>

<%@category_user.each do|examinee|%>
<tr class="updateAltrRow <%= cycle("odd", "even") %>">
<% user = User.find_by_id(examinee.userid)%>

<%if user.is_temp_examinee == 1%>
<td><%=user.login%></td>
<%else%>
<td><%=user.name%></td>
<%end%>


<td>
<%= link_to t('general.view'), :action =>"viewuserReport", :user_id=>user.id, :category_id=>examinee.categoryid, :academicYear => examinee.academicyear, :examType=>examinee.examtype%>

</td>
<td><%= link_to image_tag("excel.png", :alt=>"excel report"), :action=>"userSubjectwise", :user_id=>user.id, :category_id=>examinee.categoryid, :academicYear => examinee.academicyear, :examType=>examinee.examtype, :csv => 1%>
<td><%= link_to image_tag("pdf.png", :alt=>"pdf report"), :action=>"userSubjectwise", :user_id=>user.id, :category_id=>examinee.categoryid, :academicYear => examinee.academicyear, :examType=>examinee.examtype, :pdf => 1%>

</td>
</tr>
<%end%>

</table>

</div>

app/views/reports/_passFail.html.erb
<h2><%=t('user.examinees')%></h2>
  <%unless @category_id == 0 or @allYears.empty?%>	
    
			<table border="0" cellspacing="0">
			<tr class="updateHeader">
			<th><%=t('general.name')%></th>
			
			<th><%=t('exam.mark_scored')%></th>
			<th><%=t('exam.percent')%></th>
			<th><%=t('general.status')%></th>
			
			</tr>
			
			<%@allYears.each do|examinee|%>
			<tr class="updateAltrRow <%= cycle("odd", "even") %>">
		    <%if examinee.tempexaminee == '1'%>
			<td><%=examinee.login%></td>
			<%else%>
			<td><%=examinee.name%></td>
			<%end%>
			<td><%=examinee.score.to_f.round(2)%></td>
			<td><%=examinee.percent.to_f.round(2)%></td>
			<td><%#=examinee.status == 'p'? t('reports.pass') : t('reports.fail')%>
			<%=examinee.result_pending.to_i == 0 ? ("#{examinee.status}" == "p" ? t('reports.pass') : t('reports.fail')) : "pending"%>
			</td>
			</tr>
			<%end%>
			
			</table>
	<div class="n_s_left mt15">	<%= link_to t('reports.excel'), :action=>"generatePassfail", :category_id=>@category_id, :exam_id=>@examId, :passfail=>@passFail, :academicyear=>@academicYear, :examtype=>@examtype, :csv => 1%>	| 
	    <%= link_to t('reports.pdf'), :action=>"generatePassfail", :category_id=>@category_id, :exam_id=>@examId, :passfail=>@passFail, :academicyear=>@academicYear, :examtype=>@examtype, :pdf => 1%>	
    </div>
<%else%>
<div class="formContainer">
<%=t('not_found.no_examinees')%>
</div>
 <%end%>

app/views/reports/departmentReport.html.erb
<h2><%=t('reports.overall')%></h2>
<div class="formContainer">
     <% form_tag generateDepartmentReport_path,:method=>"get", :id=>"class_form", :class=>"assign_examinee" do -%>

            <table class="formTable" style="border:0px;">
            <tr>
            <td> 
           <div style="float:left; padding:0px; margin:0 20px 0 0;">
		   <label style="float:left; padding-right:10px; width:120px;"><%=t('general.select_cat')%>: </label>
		   <%= select_tag "examCategory",options_for_select([[t('general.select') , "" ]] + @c.collect{|p| [p.gathercat(p),p.id,{:title=>p.gathercat(p)}]},:selected=>@category_id), {:id=>"examCategory", :class=>"category w530 bdr validate[required]"} %>
		   </div>
		   <div class="clear"></div><br>
		   		   
	       <div style="float:left; padding:0px; margin:0; clear: left;">
		   <label style="float:left; padding-right:10px; width:120px;"><%=t('exam.year')%>:</label>
		   <%= select_tag 'academicYear', options_for_select(([[t('general.select'),""]] + @yrs.to_a),:selected=>@academicYear),:class=>"validate[required] w120 bdr" %>		   
		   </div>
		   <div class="clear"></div><br>		   

			<div style="float:left; padding:0px; margin:0; clear: left;">
			<label style="float:left; padding:3px 10px 0 0; width:120px;"><%=t('general.examtype')%>:</label>
			<%= select_tag 'examtype',options_for_select([[t('general.select'),""]] + @examTypes.collect{|p| [truncate(p.name,:length=>30),p.id,{:title=>p.name}]},:selected=>@examtype), {:style=>"width: 200px; height: 19px; border: 1px solid rgb(209, 209, 209);",:class=>"validate[required]"} %>
            </div>
			<div class="clear"></div><br>	
			
			<div style="float:left; padding:0px; margin:0; clear: left;">
			<%=t('reports.exl')%>: <%= radio_button_tag "fileType", 1, false,:class=>"validate[minCheckbox[1]] checkbox publish"%>
		    <%=t('reports.pd')%>: <%= radio_button_tag "fileType", 0, false,:class=>"validate[minCheckbox[1]] checkbox publish"%>
			</div>
            </td> 
			
			</tr> 

            </table>
			<%= submit_tag t('general.generate'), :id=>"assign", :class=>'btnBg' %>
	<%end%>
</div>

app/views/reports/overall.html.erb
<% unless @allYears == nil or @allYears.empty?%>
<div id="container" style="width:700px; height:400px;"></div>
<%end%>
<div style="color: #5C5C5C; float: left; font-weight: bold; padding: 0 0 12px; width: 100%; font-size:14px;"><%= t('general.filter')%></div>

<div class="formContainer">
     <% form_tag overall_path,:method=>"get", :id=>"question_filter", :class=>"assign_examinee" do -%>
            
			<div style="float:left; padding:0; margin:0 15px 0 0; width:auto;">
			<label  style="width:110px; float:left; line-height: 21px;"><%=t('exam.yr')%>:</label>
			 <%= select_tag 'academicYear', options_for_select(([[t('general.select') , "" ]] + @yrs.to_a),:selected=>@y), :class=>"validate[required] w120 bdr" %>
			</div>	
				
			<div style="float:left; padding:0; margin:0 15px 0 0; width:auto;">
			<label  style="width:110px; float:left; line-height: 21px;"><%=t('general.examtype')%>:</label>
			 <%= select_tag 'examtype_id', options_for_select(([[t('general.select'),""]] +@examTypes.collect{|p| [truncate(p.name,:length=>30),p.id,{:title=>p.name}]}),:selected=>@exam_type), :class=>"validate[required] w200 bdr" %>
			</div><div class='clear'></div>				
			<%= submit_tag t('general.filter'), :id=>"assign", :class=>'btnBg' %>
	<%end%>
</div>

<% if @organization_id == 1 or @organization_id == 2 %>
     <div class="updateStatus">
     <h2><%=t('reports.overall')%></h2>
	 <% unless @allYears.empty? or @allYears == nil%>
     <table border="0" cellspacing="0">
     <tr class="updateHeader">
     <th><%=@organization_id == 1 ? t('org.class') : t('org.course')%></th>
     <th><%=t('exam.yr')%></th>
     <th><%=t('reports.tot_examinees')%></th>
	 <th><%=t('reports.passed')%></th>
	 <th><%=t('reports.failed')%></th>
     <th><%=t('reports.pass_percent')%></th>
     <th></th>
     </tr>
	 <%@allYears.each do|ay|%>
     <tr class="updateAltrRow <%= cycle("odd", "even") %>">
     <%@displayYear = ay.currentyear%>
     <td>
	     <%="#{ay.name}"%>
     </td>
     <td>
	     <%="#{ay.currentyear}"%>
     </td>
	 <td><%="#{ay.TotalUser}"%></td>
	 <td><%="#{ay.PassedUsers.to_i}"%></td>
	 <td><%="#{ay.FailedUser}" == "" ? 0 : "#{ay.FailedUser}"%></td>     
     <td>
	     <%="#{ay.Totalpercentage.to_f.round(2)}"%>
     </td>

     <td>
	     <%=link_to t('reports.view_detail'), :action=>"specificDepartment", :course_id =>"#{ay.courseId}", :year_id=>@displayYear, :examtype_id =>@examtype_id%>
     </td>
	 
     </tr>
     <%end%>
     </table>
	 <%else%>
     <div class="formContainer">
  		<%= t('not_found.no_data')%>
 	 </div>
	 <%end%>
     </div>
<% end%>

<% if @organization_id == 3 or @organization_id == 4 %>
     <div class="updateStatus">
     <h2><%=t('reports.overall')%></h2>
	 <% unless @allYears.empty? or @allYears == nil%>
     <table border="0" cellspacing="0">
     <tr class="updateHeader">
     <th><%=t('org.course')%></th>
     <th><%=t('exam.yr')%></th>
     <th><%=t('reports.tot_examinees')%></th>
	 <th><%=t('reports.passed')%></th>
	 <th><%=t('reports.failed')%></th>
     <th><%=t('reports.pass_percent')%></th>
     <!--<th colspan="2"></th>-->
     </tr>
	 <%@allYears.each do|ay|%>
     <tr class="updateAltrRow <%= cycle("odd", "even") %>">
     
     <%@displayYear = ay.currentyear%>
     <td>
	     <%="#{ay.name}"%>
     </td>
     <td>
	     <%="#{ay.currentyear}"%>
     </td>
	 <td><%="#{ay.TotalUser}"%></td>
	 <td><%="#{ay.PassedUsers.to_i}"%></td>
	 <td><%="#{ay.FailedUser}" == "" ? 0 : "#{ay.FailedUser}"%></td>     
     <td>
	     <%="#{ay.Totalpercentage.to_f.round(2)}"%>
     </td>

     </tr>
     <%end%>
     </table>
	 	 <%else%>
     <div class="formContainer">
  		<%= t('not_found.no_data')%>
 	 </div>
	 <%end%>
     </div>
<% end%>

<script type="text/javascript">
var chart;
$(document).ready(function() {
	
	$("#question_filter").validationEngine();
	
   chart = new Highcharts.Chart({
      chart: {
         renderTo: 'container',
         plotBackgroundColor: null,
         plotBorderWidth: null,
         plotShadow: false
      },

      title: {
         text: '<b style="font-size:14px;">' + '<%=t('reports.overall_msg')%>' + ' <%=raw "#{@displayYear}"%>' +'</b>'
      },

      tooltip: {
         formatter: function() {
            return ''+
                this.series.name +': '+ this.y +' ('+ Math.round(this.percentage,2) +'%)';
         }
      },

      plotOptions: {
         pie: {
            dataLabels: {
               formatter: function() {
                  return '<b>'+ this.point.name +'</b>: '+ this.y +' %';
               }
            }
         }
      },

       series: [{
         type: 'pie',
         name: 'Percentage',
         data: [<%unless @allYears == nil%><%@allYears.each do|ay|%>
		 
            ['<%=raw truncate("#{ay.name}",:length=>20) %>', <%=raw "#{ay.Totalpercentage.to_f.round(2)}" %>],
         
         <%end%><%end%>]
      }]

   });
   
   
});


</script>









app/views/reports/pass_fail.html.erb
<% form_tag pass_fail_path,:method=>"get",:remote=>true, :id=>"class_form", :class=>"assign_examinee" do -%>
<h2><%=t('general.pass_fail')%></h2>
<div class="formContainer">
     
            <table class="formTable" style="border:0px;">
              <tr>
                
           <td> 
		   <div style="float:left; padding:0px; margin:0 20px 0 0;">
		   <label style="float:left; padding-right:10px; width:120px;"><%=t('general.select_cat')%>: </label>
		   <%= select_tag "examCategory",options_for_select([[t('general.select') , "" ]] + @c.collect{|p| [p.gathercat(p),p.id,{:title=>p.gathercat(p)}]},:selected=>@category_id), {:id=>"examCategory", :class=>"category w530 bdr validate[required]"} %>
		   </div>
		   <div class="clear"></div><br>
		   		   
	       <div style="float:left; padding:0px; margin:0; clear: left;">
		   <label style="float:left; padding-right:10px; width:120px;"><%=t('exam.year')%>:</label>
		   <%= select_tag 'academicYear', options_for_select(([[t('general.select') , "" ]] + @yrs.to_a),:selected=>@academicYear),:class=>"validate[required] w120 bdr" %>
	       </div>
		   <div class="clear"></div><br>		   

			<div style="float:left; padding:0px; margin:0; clear: left;">
			<label style="float:left; padding:3px 10px 0 0; width:120px;"><%=t('general.examtype')%>:</label>
            <%= select_tag 'examtype',options_for_select([[t('general.select') , "" ]] + @examTypes.collect{|p| [truncate(p.name,:length=>30),p.id,{:title=>p.name}]},:selected=>@examtype), {:style=>"width: 200px; height: 19px; border: 1px solid rgb(209, 209, 209);",:class=>"validate[required]"} %>
            </div>
		   

		   </td>
               </tr> 
            </table>
		
			<%#= link_to t('general.filter'),'#', :id=>"filterExam", :class=>'btnBg', :style=>"margin-top:0px !important;" %>
		   <%=link_to(content_tag('span',t('general.filter')),'#nogo',{:title=>t('general.filter'),:class=>"btnLink w105", :id=>"filterExam"}) %>
			
</div>
			<h2><%=t('general.select')%></h2>
			<div class="formContainer">
				<table class="formTable" style="border:0px;">
				<tr>
					<td> 
		    
			<div style="float:left; padding:0px; margin:0 20px 0 0;">
			<label style="float:left; padding:3px 10px 0 0; width:120px;"><%=t('exam.exams')%>:</label>
		    <%= select_tag 'examId', options_for_select([[t('general.select') , "" ]] + @exams.collect{|p| [p.name,p.id,{:title=>p.name}]},:selected=>@examId),{:style=>"width: 200px; height: 19px; border: 1px solid rgb(209, 209, 209);",:class=>"validate[required]"} %>	
            </div>
			<div class="clear"></div><br>
			<div style="float:left; padding:0px; margin:0 20px 0 0;">
			<label style="float:left; padding:3px 10px 0 0; width:120px;"><%=t('reports.pass_fail')%>:</label>
			<%= select_tag 'passfail', options_for_select(([[t('general.select') , "" ],[t('general.all') , "All" ]] + @status.to_a),:selected=>@passFail),{:style=>"width: 120px; height: 19px; border: 1px solid rgb(209, 209, 209);",:class=>"validate[required]"} %>
			</div>
			

			</td>
				</tr>
				</table>
			</div>
<%= submit_tag t('general.filter'), :id=>"assign", :class=>'btnBg', :style=>"margin-top:0px !important;" %>
<%end%>


<span id="collectUser">

	      <div class="updateStatus">
		  				
         <span class="passFail" class="n_s_left w100pc"><%=render :partial=>"passFail"%></span><br>

	    </div>
	   

</span><br>


<script type="text/javascript">

$(document).ready(function() {
     //$("#examtype").change(function() {
	 $("#filterExam").click(function() {
	  //var data = {categoryId:$("#examCategory").val(), year:$("#academicYear").val(),examType:$(this).val()};
	  var data = {
	  	categoryId: $("#examCategory").val(),
	  	year: $("#academicYear").val(),
	  	examType: $("#examtype").val()
	  };
	  var url = "<%= url_for(fetchExam_path)%>";
	  
	  			$.get(url, data, function(resp_data){
				   var arr = resp_data.examNames
				    $("#examId").empty();  
				 $("#examId").append("<option value=" + "" + ">" + "<%=t('general.select')%>" + "</option>");
				 jQuery.each(arr, function(index, value) {
					$("#examId").append("<option title='"+value.exam.name+"' value=" + value.exam.id + ">" + value.exam.name + "</option>");
				    });

		    }, 'json')
	  
	  
	  
	  
     });
	 
	 
$(".passFail .pagination a").live("click", function(){
	
	$.getScript(this.href);
	return false;
   });
	 
	 
	 
});

</script>