config/routes.rb
  post "subcategory/save"
  post "subcategory/update"
  get "subcategory/edit"
  get "subcategory/new"
  get "subcategory/destroy"
  post "subcategory/destroy"  
  
  
  get "article/index"
  get "article/show"
  get "article/list"
  get "article/comment"
  post "article/comment"
  get "article/new"
  post "article/save"
  get "article/edit"
  post "article/update"
  get "article/news"
  get "article/destroy"
  post "article/destroy"
    get "article/delete"
  post "article/delete"
  match '/getBlogcategory' => 'article#getBlogcategory'
  match '/thumbsUp' => 'article#thumbsUp'
  match '/thumbsDown' => 'article#thumbsDown'
  match '/delete_comment' => 'article#delete_comment'
  
  get "blog_category/index"
  get "blog_category/list"
  get "blog_category/show"
  post "blog_category/save"
  post "blog_category/update"
  get "blog_category/edit"
  get "blog_category/destroy"
  post "blog_category/destroy"
  get "blog_category/new"
  match '/subcategory' => 'blog_category#subcategory'
  match '/subcategory_article' => 'blog_category#subcategory_article' 
  match '/blog' => 'blog_category#blog' 
  match '/categoryArticle' => 'blog_category#categoryArticle'

  
  
  resources :users do
   get :autocomplete_user_name, :on => :collection
  end
  
  resources :folders
  get "folders/index"
  get "folders/new"
  get "folders/create"
  post "folders/create"
  get "assets/destroy"
  post "assets/destroy"  
  match "browse/:folder_id" => "folders#browse", :as => "browse"  
  match "browse/:folder_id/new_folder" => "folders#new", :as => "new_sub_folder"    
  match "browse/:folder_id/new_file" => "assets#new", :as => "new_sub_file"
  match "browse/:folder_id/rename" => "folders#edit", :as => "rename_folder"
  match '/getName' => 'folders#getName'
  match '/unshareFolder' => 'folders#unshareFolder'
  
  resources :assets 
  get "assets/index"
  get "assets/new"
  get "assets/create"
  post "assets/create"
  get "assets/destroy"
  post "assets/destroy"
match "assets/get/:id" => "assets#get", :as => "download"  
  match "assets/share" => "assets#share"
  match "assets/unshare" => "assets#unshare"
  match '/lock' => 'assets#lock'
  match '/unlock' => 'assets#unlock'  
  
  
  
  
resources :aboutus
resources :clientinfo
  resources :images 

  match '/view_aboutus' => 'home#view_aboutus'
  match '/view_clients' => 'home#view_clients'
  match '/view_features' => 'home#view_features'
  match '/view_modules' => 'home#view_modules'
  match '/view_contactus' => 'home#view_contactus'
  
  match '/deleteUsersubject' => 'users#deleteUsersubject'

match '/clientImage' => 'images#clientImage'
match '/createClientimage' => 'images#createClientimage'

  get "/questions/question_type_listing"
  post "/questions/new"
  resources :questions do
        member do
          get "delete_option"
      post "delete_option"
                get "delete_match_option"
      post "delete_match_option"
                      get "delete_matrix_row"
      post "delete_matrix_row"
                      get "delete_matrix_column"
      post "delete_matrix_column"
      get "delete_hrcl_option"
      post "delete_hrcl_option"
      
            get "saveImage"
      post "saveImage"
      
    end
  end
  match '/publish_unpublish' => 'questions#publish_unpublish'
  match '/unpublish' => 'questions#unpublish'
  match '/share' => 'questions#share' 

  match '/saveImage' => 'questions#saveImage'
   match '/sharewithCategory' => 'questions#sharewithCategory'
  match'/checkMark' => 'questions#checkMark'
   match'/viewQuestion' => 'questions#viewQuestion'
   
  get "subjects/add_subject_category"
  resources :subjects 
  
  post "subjects/cs"
  
  resources :categories
  resources :category_titles
  resources :emails  
    
  post "attend_exams/confirm_exam"
  get "attend_exams/confirm_exam"
  post "attend_exams/reject_exam"
  get "attend_exams/reject_exam"
  resources :attend_exams
  get "attend_exams/index"
  match '/examination' => 'attend_exams#examination'
  match '/instruction' => 'attend_exams#instruction'
  match '/evaluation' => 'attend_exams#evaluation'
  match '/evaluation' => 'attend_exams#ramdomizeQuestions'
   match '/examComplete' => 'attend_exams#examComplete'
   match '/calculateScore' => 'attend_exams#calculateScore'
   match '/windowClose' => 'attend_exams#windowClose'
   
   
   match 'welcome/examinee_dashboard' => 'welcome#examinee_dashboard'

  resources :exams 
  match '/scheduleExam' => 'exams#scheduleExam'
  match '/selectQuestion' => 'exams#selectQuestion'
  match '/assignQustions' => 'exams#assignQustions'
  match '/selectExaminee' => 'exams#selectExaminee'
  match '/assignExaminees' => 'exams#assignExaminees'
  match '/previewExam' => 'exams#previewExam'
  match '/deleteExamQuestion' => 'exams#deleteExamQuestion'
  match '/deleteExamUser' => 'exams#deleteExamUser'
 match '/getMark' => 'exams#getMark'
 match '/assignExam' => 'exams#assignExam'
  match '/groupExam' => 'exams#groupExam'
 match '/updateMark' => 'exams#updateMark'
  match '/examtype' => 'exams#examtype'
   match '/create_examtype' => 'exams#create_examtype'
   match '/listExamtypes' => 'exams#listExamtypes'
  match '/editExamtype' => 'exams#editExamtype' 
   match '/deleteExamtype' => 'exams#deleteExamtype' 
   match '/updateExamtype' => 'exams#updateExamtype' 
match '/getExam' => 'exams#getExam'
 match '/showEvaluationtype' => 'exams#showEvaluationtype'
 match '/hideEvaluationtype' => 'exams#hideEvaluationtype'
 match '/evaluate' => 'exams#evaluate'
 match '/getExamQuestions' => 'exams#getExamQuestions'
 match '/manualEvaluation' => 'exams#manualEvaluation'
 match '/finishEvaluation' => 'exams#finishEvaluation'
 match '/getCategoryexams' => 'exams#getCategoryexams'
 match '/assignEvaluator' => 'exams#assignEvaluator'
  match '/getEvaluator' => 'exams#getEvaluator'
  match '/evaluator' => 'exams#evaluator'
  match '/delete_evaluator' => 'exams#delete_evaluator' 
  
 match '/completedExams' => 'attend_exams#completedExams'
 match '/pendingExams' => 'attend_exams#pendingExams'
 
 
  
  match '/updateCategory' => 'category_titles#updateCategory'
  match '/deleteCategory' => 'category_titles#deleteCategory'
  
  get "settings/index"
  post "settings/update"
  
  get "feedback/index"
  match '/assign' => 'feedback#assign'
  match '/unassign' => 'feedback#unassign'
  match '/viewFeedback' => 'feedback#viewFeedback'
  match '/submitFeedback' => 'feedback#submitFeedback'
  match '/viewfeedbackResponse' => 'feedback#viewfeedbackResponse'
  match '/feedbackResponse' => 'feedback#feedbackResponse'
    

  get "reports/index"
  
  get "results/index"
  match '/usersResult' => 'results#usersResult'
  match '/resultIndex' => 'results#index'
  match '/viewUserResult' => 'results#viewUserResult'
  match '/groupResult' => 'results#groupResult'
  match '/examsResult' => 'results#examsResult'
  match '/viewExamResult' => 'results#viewExamResult'
  match '/departmentResult' => 'results#departmentResult'
  match '/viewDepartmentResult' => 'results#viewDepartmentResult'
  
  
  
  match '/userReport' => 'reports#userReport'
  match '/viewuserReport' => 'reports#viewuserReport'
 match '/examReport' => 'reports#examReport'
match '/viewexamReport' => 'reports#viewexamReport'
match '/generateUser' => 'reports#generateUser'
match '/userSubjectwise' => 'reports#userSubjectwise'
match '/generateExamReport' => 'reports#generateExamReport'
match '/departmentReport' => 'reports#departmentReport'
match '/viewDepartmentReport' => 'reports#viewDepartmentReport'
match '/generateDepartmentReport' => 'reports#generateDepartmentReport'
match '/viewDepartmentReportgraph' => 'reports#viewDepartmentReportgraph'
match '/highLevel' => 'reports#highLevel'
match '/reportYear' => 'reports#reportYear'
match '/overall' => 'reports#overall'
match '/specificDepartment' => 'reports#specificDepartment'
match '/departmentDetailed' => 'reports#departmentDetailed'
match '/semesterDetailed' => 'reports#semesterDetailed'
match '/pass_fail' => 'reports#pass_fail'
match '/generatePassfail' => 'reports#generatePassfail'
match '/fetchExam' => 'reports#fetchExam'

match '/listCategories' => 'categories#listCategories'
match '/delete_category' => 'categories#delete_category'



  get "questions/index"

  get "subjects/index"


  resources :temporary_examinee


  resources :user_registration

  
  get "welcome/index"
  get "welcome/admin_dashboard"
  get "welcome/examiner_dashboard"
  get "welcome/qsetter_dashboard"
  get "welcome/examinee_dashboard"
  post "welcome/confirm_registration"
  get "welcome/confirm_registration"
  post "welcome/reject_registration"
  get "welcome/reject_registration"
  get "welcome/user_management"
  get "welcome/workflow"
  
  get "passwords/new"

  match 'groupUser' => 'users#groupUser'
  match 'createGroup' => 'users#createGroup'
  get "user_sessions/new"

  get "users/new"
  get "users/generate_temporary_password"
  post "users/generate_temporary_password"
  match 'activate_inactivate' => 'users#activate_inactivate'
    match 'activate' => 'users#activate'
      match 'inactivate' => 'users#inactivate'

  resources :users 
  get "users/show"

  get "users/edit"
  
  
  get "home/index"

  get "user_sessions/new"
  resources :user_sessions
 
  match 'login' => "user_sessions#new",      :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout
    
  resources :password_resets do
    member do
      get 'confirmEmail'
      get 'setPassword'
      get 'savePassword'
      post 'savePassword'
      get 'verifyPassword'      
    end
  end
  get "password_resets/edit"



  get    'verify/:id'       => 'user_verifications#index'
  








    root :to => 'home#index'

app/models/feedback.rb
class Feedback < ActiveRecord::Base
  belongs_to :user
end

app/controllers/feedback_controller.rb
=begin
  feedback_controller.rb
  Description: Controller file for managing feedbacks from the user.
  Created on: April 12, 2011
  Last modified on: March 20, 2012
  Copyright 2013 PIT Solutions Pvt. Ltd. All Rights Reserved.
=end

class FeedbackController < ApplicationController
    filter_access_to :all

  def index
    @arr = [7,8]
    @question_types = QuestionType.where(["id in (?)",@arr])
    if params[:question_type].to_i == 1
    @questions = Question.where(["feedback = ?", 1]).paginate(:page => params[:page], :per_page => 10) 
    elsif params[:question_type].to_i >= 1
    @question_type_id = params[:question_type].to_i
    @questions = Question.where(["question_type_id in (?) and is_published = ? and (parent_id IS NULL or parent_id = ?)", @question_type_id,true,0]).order('created_at desc').paginate(:page => params[:page], :per_page => 10) 
    else
      @questions = Question.where(["question_type_id in (?) and is_published = ? and (parent_id IS NULL or parent_id = ?)", @arr,true,0]).order('created_at desc').paginate(:page => params[:page], :per_page => 10) 
    end
    
  end
  
  
  def assign
   feedbackQuestion = Question.where(["feedback = ?",1])
   if feedbackQuestion.empty?
     @all_published_questions = params[:question]
  
     @all_published_questions.each do|publish|
        @question = Question.find_by_id(publish.to_i)
        @question.update_attributes(:feedback => 1)
      end
       flash[:success] = t('flash_success.ques_published')
    else
       flash[:notice] = t('flash_notice.assigned_state')
    end
     redirect_to :action => "index"
 end
 
 def unassign
    all_published_questions = params[:question]
    publish = all_published_questions.split("_").last
    @question = Question.find_by_id(publish.to_i)
    if @question.feedback == 1
       @question.update_attributes(:feedback => 0)
        render :json => {:text=>true}
    else
      render :json => {:text=>false}
    end
 end
 
 def viewFeedback
   arr = [7,8]
   @questions = Question.where(["question_type_id in (?) and feedback = ?",arr,1])
 end

 def submitFeedback
   if params[:question_type_id] == '7'
        feedback = Feedback.new
        feedback.user_id = current_user.id
        feedback.question_id = params[:question_id].to_i
        if feedback.save
          @last = Feedback.find(:last)
        end

        feedback_answer = FeedbackAnswer.new
        feedback_answer.feedback_id = @last.id 
        feedback_answer.answer_id = params[:answerid].to_i
        feedback_answer.question_id = params[:question_id].to_i
        feedback_answer.save
      flash[:success] = t('flash_success.feedback_thanks')
      redirect_to :action=>:index, :controller=>:attend_exams, :user=>@current_user.id
   end
   
   if params[:question_type_id] == '8'     
     unless params[:fields] == nil
     question_ids = params[:seen].collect {|id| id.to_i} if params[:seen]
     quesLeng = question_ids.length
     
      feedback = Feedback.new
      feedback.user_id = current_user.id
      feedback.question_id = params[:parent_question].to_i
      feedback.save
      
      params[:fields].each do |i, values|
        answer_id = values["is_answer"]
        feedback = Feedback.new
        feedback.user_id = current_user.id
        feedback.question_id = question_ids[i.to_i-1]
        if feedback.save
          @last = Feedback.find(:last)
        end
       
        feedback_answer = FeedbackAnswer.new
        feedback_answer.feedback_id = @last.id 
        feedback_answer.answer_id = answer_id.to_i
        feedback_answer.question_id = question_ids[i.to_i-1]
        feedback_answer.save
      end
      flash[:success] = t('flash_success.feedback_thanks')
      redirect_to :action=>:index, :controller=>:attend_exams, :user=>@current_user.id
    else 
      flash[:notice] = t('flash_notice.select_one_option')
      redirect_to :back
    end 
   end

 end
 
 def feedbackResponse
   sql = "SELECT  distinct Q.id 
          FROM       feedbacks F 
          Inner Join questions Q on Q.id = F.question_id;"
    @feedbackResponses = Feedback.find_by_sql(sql)

 end
 
 def viewfeedbackResponse
   @question = Question.find_by_id(params[:question_id].to_i)
   @subQuestions = Question.where(["parent_id = ?",@question.id])
   answers = Answer.find_all_by_question_id(@question.id)
 end

end

app/helpers/feedback_helper.rb
module FeedbackHelper
end

app/views/feedback/_collectFeedback.html.erb
<div class="qestionhead"><h3><%if @question_type_id%><%=@question_type_name%> <%=t('general.questions')%><%else%><%=t('question.all_question')%><%end%> </h3>
<p class="showComment paginationDiv floatR" style="color:#db3939; font-style:italic; font-size:14px; display:inline"></p>
</div>
<% unless @questions.empty?%>
<% form_tag assign_path, :method=>"get", :id=>"class_form", :class=>"assign_question" do -%>

<div class="questionTabele">
<table border="0" cellspacing="0">
<tr class="updateHeader">
<th><%=t('general.name')%></th>
<th><%=t('question.ques_type')%></th>
<th class="alignC"><%=t('general.assign')%></th>



</tr>


<%@questions.each do|question|%>
<tr class="updateAltrRow <%= cycle("odd", "even") %>">

<td><%= link_to truncate_html(strip_links(question.description)), :controller => "questions", :action=>"viewQuestion", :question=> question.id%><span id="question_share_<%=question.id%>"></span></td>
<td>
 	<%qt=QuestionType.find_by_id(question.question_type_id)%>
 	<%=qt.name%>
</td>

<td class="alignC">

       <%if (current_user.role_id == Admin or current_user.role_id == Examiner)or (question.user_id == current_user.id)%>
       	<%= check_box_tag "question[]", question.id, question.feedback==1 ? true : false, {:class=>"validate[maxCheckbox[1],[minCheckbox[1]] publish checkbox alignV", :id=> "question_#{question.id}"} %>
       <%else%>
       <%=t('feedback.published')%>
       <%end%>
</td>

</tr>
<%end%>
</table>
<%= submit_tag t('general.assign'), :id=>"assign", :class=>'btnBg' %>
 
	<%= will_paginate @questions, 
                :prev_label => t('general.previous'), 
                :next_label => t('general.next'),
                :page_links =>true,           
                :renderer => PaginationListLinkRenderer
              %>
<%end%>

</div>
<%else%>
<div class="formContainer">
  <%=t('not_found.no_que_found')%> 
 </div>
 <%end%>

			  
<script type="text/javascript">	
	$(document).ready(function() {

		$('.publish').click(function(){
			var thischeck = $(this);
			if (!(thischeck.is (':checked'))){
				var target = '<%= url_for(unassign_path)%>';
				var unpublished_target = target + "?question=" + this.id
				$.get(unpublished_target,$("#" + this.id).serialize(),function(data){
					if (data.text == true){
						$(".showComment").empty();
						$(".showComment").append("<%=t('feedback.ques_unassigned')%>").delay(500);
						setTimeout(function() {
				     		$(".showComment").empty();
				     	}, 2000);
		            }
	      		});
	 		}
		});
		
		
		$("#collectQuestion .pagination a").live("click", function(){
		
		var link = this.href
			var lastChar = link.substr(link.length - 1);	
			if (lastChar == '#'){
				return false;
			}
			else{
				$.getScript(this.href);
				return false;
			}
		});
	});
</script>

app/views/feedback/_question_description.html.erb
<div class="question_desc_feedback">
	<table>
  		<% qustionType = QuestionType.find_by_id(@question.question_type_id)%>
	  	
	  	<tr>
			<td class="container_desc">
        		<span class="toggle" id="<%= @question.id %>"></span>
        		<div class="decsription"><%= @question.description.html_safe %></div>
    		</td>
                
	  	</tr>
    </table>
</div>

app/views/feedback/feedbackResponse.html.erb
<% @collect = []%>
<%@feedbackResponses.each do|fr|%>
<%question = Question.find_by_id(fr)%>
<%unless question.description == nil%>
<% @collect << fr%>
<%end%>
<%end%>

<div class="updateStatus">

<h3>Feedback Responses</h3>
<%unless @collect.empty?%>
<table border="0" cellspacing="0">
<tr class="updateHeader">
<th>Question</th>
<th>View Response</th>
</tr>


<% @collect.each do|responseQuestion|%>
<tr class="updateAltrRow <%= cycle("odd", "even") %>">
<%question = Question.find_by_id(responseQuestion)%>
<%unless question.description == nil%>
<td><%= truncate_html(strip_links(question.description)) %></td>
<td>
 	<%= link_to "View", :action=>"viewfeedbackResponse", :question_id=>question.id%>
</td>
<%end%>
</tr>
<%end%>

</table>
<%else%>
<div class="formContainer">
  No feedback responses. 
 </div>
 <%end%>
</div>

app/views/feedback/index.html.erb
<h2><%=t('general.filter')%></h2>

<%= form_tag '/feedback/index', :method=>"get", :id=>"question_filter", :class=>"assign_question" do -%>


<div class="formContainer">
            <table class="formTable" style="border:0px;">
              <tr>
                <td><div style="float:left; padding:0px; margin:0 20px 0 0;">
				<label style="float:left; padding-right:10px; width:auto;"><%=t('feedback.select_ques')%></label>
				<%= select_tag "question_type", options_for_select([[t('general.all'),0],[t('feedback.assigned'),1]] + @question_types.collect{ |q| [q.name, q.id] }),:class=>"validate[required] w120 bdr"%>
				</div>
				</td>
                </tr> 
            </table>
		<%= submit_tag t('general.filter'), :id=>"filter", :class=>'btnBg' %>	
</div>

<%end%>


<div class="updateStatus">

<span id="collectQuestion"><%=render :partial=>"collectFeedback"%></span><br>




</div>

<script type="text/javascript">	
$(document).ready(function() {

		//$('.publish').click(function(){	
			$('.publish').click(function(){
				var thischeck = $(this);
				if (thischeck.is (':checked')){


				}
                                
                   else{
                                  var target = '<%= url_for(unassign_path)%>';
                                  var unpublished_target = target + "?question=" + this.id
                                  $.get(unpublished_target,$("#" + this.id).serialize(),function(data){
                                    if (data.text == true){
				    $(".showComment").empty();
                    $(".showComment").append("Feedback question unassigned.").delay(2000);
							setTimeout(function() {
						     $(".showComment").empty();
						     }, 5000);
                                    }
                                  });
                                }

        });
		
		
		$("#collectQuestion .pagination a").live("click", function(){
	
	var link = this.href
	var lastChar = link.substr(link.length - 1);	
	if (lastChar == '#'){
		return false;
	}
	else{
		$.getScript(this.href);
		return false;
	}
   });
                        });
  </script>

app/views/feedback/index.js.erb
$("#collectQuestion").html("<%= escape_javascript(render("collectFeedback"))%>")

app/views/feedback/viewFeedback.html.erb
<div class="feedBackStatus">
<h3><%=t('feedback.give_your')%></h3>
<%unless @questions.empty?%>
          <%@questions.each do|question|%>
          <% @question = question%>
		  <%if @question.question_type_id == 7%>
		  <% @feedback_given = Feedback.find_by_user_id_and_question_id(current_user.id,@question.id)%>
		  <%if @feedback_given == nil%>

		  <%= form_tag "/submitFeedback", :method => :post, :id => 'class_form', :class=>"formExam" do %>
            
                 
		          <%=render :partial=>"question_description", :locals=>{:question=>@question}%>
		  
				    <table class="answer_name" id="toggle_<%=@question.id%>">
					 	
						<tr><td>
						<%= hidden_field_tag "question_type_id", @question.question_type_id%>	
			            <%= hidden_field_tag "question_id", @question.id%>	
					   <% answers = Answer.find_all_by_question_id(@question.id)%>
					   <%answers.each do|answer|%>
						   <%= radio_button_tag :answerid, answer.id,false, {:class=>"validate[required] radio publish", :style=>"margin-right: 5px;"} %>
						    <span title="<%=answer.name%>"><%= text_field_tag :answer,truncate(answer.name,:length=>25), :style=>"width:200px; height:19px; border:#d1d1d1 1px solid; text-align:center;", :disabled => true%></span>
							<br><br>
					   <%end%>
					   </td></tr>
					 </table>
					 <%= submit_tag "Submit", :class=>'btnBg', :id=>"examNext" %>
		          <%end%>
		    	 
           
		 	<%else%>
		  </div>
          <%=t('feedback.given')%>
		  </div>
        <%end%>  
		<%end%>
		
		<% @feedback_given = Feedback.find_by_user_id_and_question_id(current_user.id,@question)%>
		<%if @question.question_type_id == 8%>
		  <%if @feedback_given == nil%>   
		  
        <%= form_tag "/submitFeedback", :method => :post, :id => 'class_form', :class=>"formExam" do %>
		 
		  <%=render :partial=>"question_description", :locals=>{:question=>@question}%>
		    <%= hidden_field_tag "question_type_id", @question.question_type_id%>	
		    <%@sub_questions = Question.where(["parent_id = ?", @question.id])%>

					<%@ans = Answer.where(["question_id = ?",@question.id])%>	 
					<%@ans_length = @sub_questions.length%>
			        <table cellpadding="0" cellspacing="0" border="0" class="tblRepeter  bt0 bl0" id="toggle_<%=@question.id%>" style="width:100%!important">
			        
					<tr>
		  				<div class="tblCols rowValue">	
						<td style="border-left:1px solid #D1D1D1; width:20%; text-align:center;">&nbsp;</td>
						<%@sub_questions.each do|a|%>
				         <td style="border-left:1px solid #D1D1D1; min-width:80px;width:auto!important;width:80px; text-align:center;" class="td_v_mid" title="<%=a.name%>">
				         	  <%= label_tag :question,truncate(a.name,:length=>25), :style=>"min-width:80px;width:auto!important;width:80px; display:inline; padding: 0 5px; word-wrap:break-word;  text-align:center; padding:0px; line-height:18px;", :disabled => true, :id=>a.id%>
						    <%= hidden_field_tag('seen[]', a.id) %>
						 </td>	
						<%end%>
		 				</div>
					</tr>
						
						 
					    <%count = 0%>
		  				<div class="tblCols rowValue">	
						<%@ans.each do|s|%> 
			    		<tr align="center">
						<td style="border-left:1px solid #D1D1D1; width:25%;" class="td_v_mid" title="<%=s.name%>">
			    			<%= label_tag :answer,truncate(s.name,:length=>25), :style=>"min-width:80px;width:auto!important;width:80px; display:inline; padding: 0 5px; word-wrap:break-word;  text-align:center; padding:0px; line-height:18px;", :disabled => true, :id=>s.id%>
						</td>
						   
							<%for i in (1 .. @ans_length)%>
							<td class="td_v_mid" style="text-align:center;border-left:1px solid #D1D1D1;">
                             <span style="text-align:center; "><%= radio_button_tag "fields[#{i}][is_answer]", s.id, false, :class=>"validate[required] radio" %></span>
							</td>
							<%end%>	
							<%count = count + 1%>
						</tr>
						<%end%>
		 				</div>
				    
                        <%= hidden_field_tag'parent_question', @question.id %>
						
					</table>	
					<div class="clear"></div>
			  <%= submit_tag t('general.submit'), :class=>'btnBg', :id=>"examNext" %> 
		 <%end%>
                 
                
        
	    <%else%>
		<div class="formContainer">
          <%=t('feedback.given')%>
		</div>
        <%end%>	
		<%end%>	

<%end%>

<%else%>
<div class="formContainer">
<%=t('not_found.no_feedback')%>
</div>
<%end%>
</div>